### ISSUE TITLE
I want to add 2 features .

### ISSUE THREAD

**Issue by abhay-raj19** [nvralone/site#11]
*1.*  I want to add a  pre page loader:
> A loader that loads in the beginning of the page and finally loads to the main page.
> Time for loading is 2-3 sec.

*2.*  And  button for navigating to the top of the page.
> The button will be added in bottom right corner of the page and on clicking on it it directly takes you to the top of the page.

Pls Assign me (@pvrzz ) for the best suggested changes , I will make it more awesome.

**Comment by pvrzz** [comment]
Apologies for the late response! I had a lot going on the past few days. This sounds great! Definitely assigning you. <3
